name: Deploy
on: 
  workflow_dispatch:
  push:
  
jobs:
  deploy:
    if: github.actor != 'github-actions[bot]' 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      # Deploy for website
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: bobartelie/site
          publish_branch: main
          publish_dir: site/_site
          commit_message: "Deploy site [skip ci]"
      # Deploy for app
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: bobartelie/app
          publish_branch: main
          publish_dir: app/_site
          commit_message: "Deploy app [skip ci]"